# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone_number', models.IntegerField()),
                ('years_experience', models.IntegerField()),
                ('work_experience', models.TextField()),
                ('about_you', models.TextField()),
            ],
        ),
    ]
