# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-14 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
