# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20200614_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_your_applying_for',
            field=models.CharField(default='', max_length=50),
        ),
    ]
