# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('author', models.CharField(default='', max_length=30)),
                ('description', models.TextField()),
                ('photo_type', models.CharField(choices=[('Still Life', 'Still Life'), ('Adventure', 'Adventure'), ('Nature', 'Nature'), ('Irishness', 'Irishness')], default='Still Life', max_length=100)),
                ('available_in', models.CharField(choices=[('Gloss', 'Gloss'), ('Canvas', 'Canvas'), ('Framed', 'Framed')], default='Gloss', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('port_or_land', models.CharField(choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait')], default='Portrait', max_length=100)),
                ('product_id', models.CharField(default='shutter#', max_length=20)),
            ],
            options={
                'ordering': ['photo_type'],
            },
        ),
    ]
