# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='shutter#', max_length=20),
        ),
    ]
