# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default='photography', max_length=100),
        ),
    ]
