# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200526_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prdouct_id',
            new_name='product_id',
        ),
    ]
