# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200526_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='port_or_land',
            field=models.CharField(choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait')], default='Portrait', max_length=100),
        ),
    ]
