# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200605_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_type',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Product', 'Product'), ('Nature', 'Nature'), ('Irishness', 'Irishness')], default='Lifestyle', max_length=100),
        ),
    ]
