# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200605_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_type',
            field=models.CharField(choices=[('Still Life', 'Still Life'), ('Adventure', 'Adventure'), ('Nature', 'Nature'), ('Irishness', 'Irishness')], default='Still Life', max_length=100),
        ),
    ]
